# Site wide configuration

title: 
locale: en_US
description: Bits and pieces from a Maths and Econ Geek
logo: LucaASCII.svg
url:

# Jekyll configuration

collections:
- slides


permalink:   /:categories/:title/
markdown:    kramdown

sass:
  sass_dir: _sass
  style: compressed


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false
  input: GFM

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

comments: true

# Site owner
owner:
  name: Luca Verginer
  avatar: luca-verginer-8bit.png
  email: luca.v@verginer.eu
  disqus-shortname: MatEcon
  twitter: lucaverginer 
  facebook: 
  github: verginer
  stackexchange: 
  bitbucket: alucaria
  linkedin:
  instagram: 
  flickr:
  tumblr:
  pinterest:
  weibo:
  google:
    plus: 
    analytics: UA-5673135-4
    verify: 
    ad-client:  
    ad-slot: 
  bing-verify: 
